---
driver:
  name: vagrant
  customize:
    cpus: 4
    memory: 2048

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[et_cassandra::default]
      - recipe[et_cassandra::opscenter]
      - recipe[cassandra_fake_data::default]
    attributes:
      ec2:
        placement_availability_zone: us-east-1b
      et_cassandra:
        env:
          jvm_opts:
            - -XX:+CMSConcurrentMTEnabled
            - -XX:ConcGCThreads=6

  - name: opscenter
    run_list:
      - recipe[et_cassandra::opscenter]
      - role[cassandra_opscenter]
    attributes:
      ec2:
        placement_availability_zone: us-east-1b
      et_cassandra:
        opscenter:
          cluster:
            managed: true
            config:
              jmx:
                username: ''
                password: ''
                port: 7199
              cassandra:
                username: ''
                seed_hosts: '0.0.0.0'
                api_port: 9160
                password: ''
