---
driver:
  name: ec2
  require_chef_omnibus: 12.10.24
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids:
    - ci-testing
  instance_type: c3.large
  interface: public
  iam_profile_name: test-et-cassandra
  tags:
    Env: public
    Type: test

transport:
  name: sftp
  username: ubuntu
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: cloud-default
    driver:
      tags:
        Name: et_cassandra-cloud-default-ubuntu-1404
    run_list:
      - recipe[ec2test::default]
      - recipe[et_logger::forwarder]
      - recipe[et_cassandra::default]
      - recipe[et_cassandra::opscenter]
      - recipe[et_cassandra::backups]
      - recipe[cassandra_fake_data::default]
    attributes:
      et_logger:
        generate_cert: true
      et_cassandra:
        snapshot:
          data_bag: false
          wait_secs: 1
          tar_retry_secs: 0
          tar_retries: 1
          upload_retries: 1
          upload_retry_delay: 0
        incrementals:
          upload_retry_delay: 0
          tar_retries: 1
          upload_retries: 1
        snapshot_conf:
          SKIP_KEYSPACES: (system_traces OpsCenter)
          BUCKET: et-cassandra-backups-test
        config:
          memtable_heap_space_in_mb: 1
        mocking: true
        env:
          jvm_opts:
            - -XX:+CMSConcurrentMTEnabled
            - -XX:ConcGCThreads=6

  - name: cloud-opscenter
    driver:
      tags:
        Name: et_cassandra-cloud-opscenter-ubuntu-1404
    run_list:
      - recipe[ec2test::default]
      - recipe[et_cassandra::default]
      - recipe[et_cassandra::opscenter]
      - role[cassandra_opscenter]
    attributes:
      et_cassandra:
        mocking: true
        opscenter:
          cluster:
            managed: true
            config:
              jmx:
                username: ''
                password: ''
                port: 7199
              cassandra:
                username: ''
                seed_hosts: '0.0.0.0'
                api_port: 9160
                password: ''
