---
driver:
  name: vagrant
  customize:
    cpus: 4
    memory: 2048

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[et_cassandra::default]
      - recipe[et_cassandra::opscenter]

  - name: opscenter
    run_list:
      - recipe[et_cassandra::opscenter]
    attributes:
      et_cassandra:
        opscenter:
          master: true
