language: ruby
rvm:
- 2.2
sudo: required
dist: trusty
cache:
  directories:
  - "$HOME/.berkshelf"
addons:
  apt:
    sources:
    - chef-stable-precise
    packages:
    - chefdk
env:
  global:
  - KITCHEN_YAML=.kitchen.cloud.yml
  - secure: X2sTENP5OzTbAX0LYfYbYgyyg7QNLmh5gSLXpeo1YWIQy7WFbsyzqOBONSi6U7CrvXmn182C9z6yPX9EXgormp6vse6vWHmsrL+40/oL4MON4PAmbTYTSima+EBCxT0MYV6NMyDlZr+6bJkRTQ+3IbbGa66xbXEnLtKernFDyPA=
  - secure: EO3XMHXeFfexDdaITVkkXiVNOdZGcnBExlxb0kFwv6gvEhP7y8yrhB2advArmEZCdCW2BJh9G6eMf7oyBKpwzviIEHqttpJaRqofyo+bkcdSo3+sHmfh1NdgnVkxEhmX3xhcihMvraxLmWxAoRHijb7eU8WIH9CF+ZOOVYNb8NY=
before_install:
- openssl aes-256-cbc -K $encrypted_5ffda6c121fc_key -iv $encrypted_5ffda6c121fc_iv
  -in travis_ci_ec2.pem.enc -out ~/.ssh/travis_ci_ec2.pem -d
- mkdir ~/.chef
- touch ~/.chef/knife.rb
- chmod 600 ~/.chef/knife.rb ~/.ssh/travis_ci_ec2.pem
- chef --version
- eval "$(chef shell-init bash)"
- rubocop --version
- foodcritic --version
install:
- chef gem install kitchen-ec2
- berks
script:
- rubocop
- foodcritic .
- kitchen test -d always -c
